# Generated by Django 2.0.2 on 2018-04-25 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_trip_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion_model',
        ),
    ]
