# Generated by Django 2.0.2 on 2018-04-25 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_suggestion_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_model',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
