# Generated by Django 2.0.2 on 2018-04-25 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_trip_model_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip_model',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='trip_model',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
