# Generated by Django 2.0.2 on 2018-05-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180510_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trips',
            field=models.ManyToManyField(to='myapp.Trip'),
        ),
    ]
