# Generated by Django 2.0.2 on 2018-05-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_profile_trips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='trips_total',
            field=models.IntegerField(default=0),
        ),
    ]
